### ISSUE TITLE
requires python 3.6

### ISSUE THREAD

**Issue by kaymueller** [justinpearson/Raspberry-Pi-for-iPhone-Backup#1]
Hi there!

before python 3.6 there was no print(f which end's up throwing syntax errors when running the python script. Should be mentioned somewhere, because my raspi is pretty much vanilly and only had python 3.5.
___

   File "/home/pi/backup-iphone.py", line 17
    print(f'{datetime.now()}: Welcome to backup-iphone.sh!')
                                                          
SyntaxError: invalid syntax

**Comment by justinpearson** [comment]
Thanks for pointing that out! I'll add a warning to the README: https://github.com/justinpearson/Raspberry-Pi-for-iPhone-Backup/commit/8ac18365082ee2739572e8e3aff1a44b1bac9c81

(I really like f-strings, and I think Python 3.7 comes default on Raspbian that's based on Debian Buster, so I think I'll just warn the user instead of going back to using `'x = {}'.format(x)` :)
